{
 "title": "Borges",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Pending repositories",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*) from repositories where status = 'pending' AND $__timeFilter(created_at);\n"
    }
   ]
  },
  {
   "title": "Fetched repositories",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*) from repositories where status = 'fetched' AND $__timeFilter(fetched_at);\n"
    }
   ]
  },
  {
   "title": "Erroed repositories",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*) from repositories where status = 'pending' and fetch_error_at is not null AND $__timeFilter(fetch_error_at);\n"
    }
   ]
  },
  {
   "title": "Not Found repositories",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*) from repositories where status = 'not_found' AND $__timeFilter(fetch_error_at);\n"
    }
   ]
  },
  {
   "title": "Auth required repositories",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*) from repositories where status = 'auth_req' AND $__timeFilter(fetch_error_at);  \n"
    }
   ]
  },
  {
   "title": "Last 10 fetched repositories",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT endpoints[1], $__time(fetched_at) from repositories where status = 'fetched' AND $__timeFilter(fetched_at) order by fetched_at desc limit 10;"
    }
   ]
  },
  {
   "title": "Top repositories with more references",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 3 },
   "targets": [
    {
     "rawSql": "select \n  repo.endpoints[1], \n  count(refs.repository_id),\n  $__time(repo.fetched_at)\nfrom repositories as repo \ninner join repository_references as refs \n  on refs.repository_id = repo.id \nwhere repo.status = 'fetched' AND\n$__timeFilter(fetched_at)\ngroup by repo.id \norder by count(refs.repository_id) DESC \nlimit 10;"
    }
   ]
  },
  {
   "title": "TTF (Time To Fetch)",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 5, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select AVG((fetched_at - created_at)) as time_to_fetch from repositories where status = 'fetched' AND $__timeFilter(fetched_at) LIMIT 1;"
    }
   ]
  },
  {
   "title": "Repositories per day",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "repositories" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date_trunc('day', fetched_at) AS time,\n count(*) as \"fetched repositories per day\"\nFROM\n  repositories\nWHERE\n  status = 'fetched' AND\n  fetched_at is not null\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\n date_trunc('day', fetch_error_at) AS time,\n count(*) as \"erroed repositories per day\"\nFROM\n  repositories\nWHERE\n  status = 'pending' AND\n  fetch_error_at is not null\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\n date_trunc('day', created_at) AS time,\n count(*) as \"created repositories per day\"\nFROM\n  repositories\nWHERE\n  status = 'pending' AND\n  created_at is not null\nGROUP BY time"
    }
   ]
  }
 ]
}